name: craze
version: 0.1.2.0
synopsis: HTTP Racing Library
description: A micro-library for racing HTTP GET requests
maintainer: Eduardo Trujillo <ed@chromabits.com>
license: MIT
github: etcinit/craze
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - curl
  - bytestring
  - transformers
  - text
  - mtl
  - lifted-async
  - lifted-base
  - monad-control
  - transformers-base
  - lens

library:
  source-dirs: src
  dependencies:
    - async
    - data-default-class
    - containers

executables:
  craze-example:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -fno-warn-unused-do-bind
    main: Main.hs
    source-dirs: app
    dependencies:
      - craze
      - optparse-generic

tests:
  craze-spec:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -fno-warn-unused-do-bind
    main: Spec.hs
    source-dirs: test
    dependencies:
      - craze
      - hspec
      - hspec-discover
      - http-types
      - haxy
      - HTTP
  craze-doctest:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -fno-warn-unused-do-bind
    main: Doctest.hs
    source-dirs: test
    dependencies:
      - craze
      - doctest
      - doctest-discover
